### ISSUE TITLE
No Custom CSS Panel in Appearance > Customize

### ISSUE THREAD

**Issue by g2creative** [elementor/hello-theme#108]
Apologies if I've overlooked something - I'm new. I'm using Hello theme 2.2.2 with Elementor Pro 2.8.2. I don't see a "Custom CSS" panel inside the Appearance > Customize panel. When I edit the theme, there is a link that takes me to a Custom CSS panel, but nothing there is editable.  I was asking in a Facebook group about this and others using the Hello theme do see a custom CSS panel inside Appearance > Customize, but it is totally missing from my version of the Hello Theme. Screenshots attached.
<img width="296" alt="Screen Shot 2019-12-28 at 9 15 51 AM" src="https://user-images.githubusercontent.com/53616239/71545222-bfcc8780-2956-11ea-82b4-df73329394ad.png">
<img width="1226" alt="Screen Shot 2019-12-28 at 9 17 44 AM" src="https://user-images.githubusercontent.com/53616239/71545223-bfcc8780-2956-11ea-8698-9cce7529dbd5.png">
<img width="1375" alt="Screen Shot 2019-12-28 at 9 18 06 AM" src="https://user-images.githubusercontent.com/53616239/71545224-bfcc8780-2956-11ea-9237-eee0eb12e368.png">
![80546825_10219086723586683_1362058790987366400_n](https://user-images.githubusercontent.com/53616239/71545231-ceb33a00-2956-11ea-8caf-35ca4dcfe56f.jpg)

**Comment by g2creative** [comment]
Maybe answering my own question here ... is the additional CSS component only available on a Child theme?

**Comment by arielk** [comment]
It's work out of the box, do not know about any problem with this.
