### ISSUE TITLE
Option to hide page title in theme customizer

### ISSUE THREAD

**Issue by tomas-eklund** [elementor/hello-theme#111]
Is there any particular reason why Hello Elementor doesn't utilize the WordPress theme customizer? 

The one thing that annoys me the most about Hello Elementor is that it isn't the blank canvas theme it promises to be. The page title - which is outputted by default in `single.php` - completely ruins the layout of all pages.

I've read the discussion on issue #81, asking users to add code to `functions.php`, but isn't the ultimate purpose of Elementor to give users without coding skills the power to have full creative freedom in designing their sites? Asking people to create a child theme and writing PHP code is, I presume, as far from the core philosophy behind Elementor as you can get. The alternative, having to go into the Page Settings of every single page on the site to hide it, isn't a lot better. 

Would it be ok to ask for this to be a theme customization setting? I have implemented the functionality myself and could submit a pull request, but I'm not a WordPress theme developer and it would be my first time contributing to an open-source project, so I suppose I could use some guidance and someone checking my code.

![image](https://user-images.githubusercontent.com/1409791/73353380-8196f080-4293-11ea-86cd-a0ae5710985d.png)

**Comment by shilo-ey** [comment]
Hi @tomas-eklund 

Thanks for your feedback.

Once you use Elementor to build your site, you actually no longer need this code, since once you switch off the option in Elementor editor, it won't be printed in the markup.

As for adding control to select this option globally for the entire site - it's an Elementor feature request, and as I can see you already mentioned it there.

Thanks again.

**Comment by tomas-eklund** [comment]
I don't agree. It is the theme (Hello Elementor) that outputs the title. Why shouldn't it also be the responsibility of the theme to also allow hiding it? If you chose a different theme, there is no need to hide the title in Elementor because most other themes either don't show the title or allow yout to hide it using the customizer.

Another point is that it is so easy to add the customization option. It could be done today. We have been waiting for global styling settings in Elementor for ages. And seing how [you prioritize things](https://elementor.com/blog/4-million-active-installs/) (flashy stuff for marketers over boring but useful basic features) I doub't that we will see the Elementor global setting to hide the title anytime soon.

By the way, I couldn't find the Elementor feature request for this,
