### ISSUE TITLE
style.min.css styles wins child theme style.css even with Disable Default Fonts enabled

### ISSUE THREAD

**Issue by seanvandermolen** [elementor/hello-theme#113]
Have some global styles in the hello child theme

In builder and view those styles are replaced by style elements in style.min.css

**Comment by zeinnicholas** [comment]
Enqueue your child theme stylesheet later, or in_array() after the parent theme's stylesheet.

I don't see how this is an issue with the theme. It's more like you are using your child theme wrongly.
