### ISSUE TITLE
Issue with WPAdverts categories pages

### ISSUE THREAD

**Issue by pixyweb** [elementor/hello-theme#115]
Hello, 
I'm having an issue with the WPAdverts plugin. When using Elementor with Hello theme the WPAdverts categories do not work. Instead of the adverts I  get a cannot be find page.   I tried to switch to Twenty Twenty WP theme and it works well.   
Hope you can help, thanks.   
Greg

**Comment by VonZubinski** [comment]
I had the same issue. Try to follow the Plugin Developers recommendation here:
https://wpadverts.com/documentation/child-themes-and-templates/

Worked for me - Good luck

**Comment by VonZubinski** [comment]
@pixyweb The plugin developer came trough to help:
https://wordpress.org/support/topic/hello-elementor-theme-missing-categories-and-location-pag/
