### ISSUE TITLE
Global Code Input

### ISSUE THREAD

**Issue by nfspck** [elementor/hello-theme#121]
Hi, I really love how light the theme is but there is one thing I really miss from the previous theme I used (Beaver Theme) and that was the ability to add code, like tracking/analytics or JS code directly in the customizer.  That theme allowed me to add code between the head tags, header tags, and footer tags but also gave a separate field for global JS, all of which are extremely convenient and removed the risk of others messing something up when working in a header or footer PHP template file.

Example of the location and options
https://snipboard.io/YX5HDx.jpg

Example of code input
https://snipboard.io/3sCTRE.jpg

Is this something that can be considered for the theme in the future?

**Comment by smcirvin** [comment]
I strongly agree with this request! Now that Elementor has "theme styler", the header and footer code areas (like competing themes have) are the only things missing that makes the Hello/Elementor combination work as a universal starting point for most folks. Please make this a feature in the next version! :)

**Comment by KingGrizzly** [comment]
Yeah, global scripts could be handy just like the global CSS is.

**Comment by BrandonRall** [comment]
I'd love a feature like this. It'd eliminate the need for additional plugins (or editing of template files) to implement fairly standard platforms like Google Analytics and Google Tag Manager.

**Comment by gilesholder** [comment]
I would love this as well but guess it falls under more elementor than the hello theme.

**Comment by gilesholder** [comment]
This is now includes in elementor 3.1. Guess this issue can b closed 😀
