### ISSUE TITLE
WP media gallery is show using only one column instead of columns value set in gallery settings 

### ISSUE THREAD

**Issue by efintina** [elementor/hello-theme#123]
Using standard wp media gallery, regardless of columns value set, Hello Theme display it using single column on desktop device.

**Comment by kellyrenee814** [comment]
Same issue. The issue is not plug-in related.

**Comment by now4dw** [comment]
I see there was no solution offered and I am having the same issue in March, 2021 :(

**Comment by nickrobinsonloops** [comment]
Had the same problem for months. It's only the hello theme, which AFAIK doesn't have much css. Damn annoying.

**Comment by now4dw** [comment]
I solved this problem by adding the Meow Gallery Pro plugin at https://meowapps.com/ . I tried other similar plugins first and then remembered this one from a previous experience. Works a treat. I also use their lightbox. You can see both working at https://theownerbuildernetwork.co/ideas-for-your-rooms/interesting-entries/ 
Hope that helps.

**Comment by nickrobinsonloops** [comment]
I found a solution - I copied the css for wp-media-gallery  into the theme & all is well.

**Comment by ledovej** [comment]
> I found a solution - I copied the css for wp-media-gallery into the theme & all is well.

Could you post the css code here?

**Comment by nirbhay18** [comment]
@ledovej https://gist.github.com/nirbhay18/db3247dac9664cf134fb38bb80271c5a

**Comment by arielk** [comment]
Hi @efintina,

Long time, but this option seems to be deprecated in new official WP themes, so for now you can use the CSS code that [[nirbhay18](https://github.com/nirbhay18)](https://github.com/elementor/hello-theme/issues/123#issuecomment-1158464644) mentioned above.

Thanks for the feedback!
