### ISSUE TITLE
Use only semi transparent colors that look acceptable on a light or dark background

### ISSUE THREAD

**Issue by vovkasolovev** [elementor/hello-theme#126]
The theme has elements with colors that look good only on a white background. On a colored background, these colors look out of place.I Suggest that you do not use opaque colors in the theme.

For example, the theme has an indication for coloring a table through a row. 

  table tbody > tr:nth-child(odd) > th {background-color: #**eeeeee**; }
  table tbody tr:hover > th {background-color: #**e9e9e9**; }
  table tbody + tbody {border-top: 2px solid #**cccccc**; }

I believe that this unnecessary element should only be present in the form of a translucent color, for example, replace the #eeeeee color with #bbbbbb40. This approach is more universal, for cases if it is necessary to specify the color.

The values of colors and transparency should be selected to look acceptable on any background color.

**Comment by arielk** [comment]
@vovkasolovev Do you have any example how to convert those colors to HEX 8-digits or to RGBA?

**Comment by vovkasolovev** [comment]
FF-%% = opacity for #000 or 80-%%/2 = opacity for #808080, where %% is two digits from original #%%%%%% gray.
But This shouldn't be done by math, because mid gray should be tweaked to be more white and with alpha transparency to be acceptable to work for eyes on any background. This task should be done by designer.
