### ISSUE TITLE
Sitewide CSS for Gravity Forms

### ISSUE THREAD

**Issue by bryanlongSM** [elementor/hello-theme#129]
I am running Elementor Pro 2.10.3 with a Hello Child Theme. I have Gravity Forms 2.4.19 and Ultimate Addons 1.26.1 installed.

I know how to make changes to individual forms on specific pages using both Ultimate Addons Gravity Forms and on Page CSS.

Is there a way to set basic style for all Gravity Forms on my website via CSS?

I have tried to disable the Gravity Forms styles via Functions.php and add my own sitewide stylesheet. I'm able to break the out-of-the-box style but I can't find a way to have my new code function. I have added code to style.css and I have added my own stylesheet gravityforms.css.

I'm running out of ideas. Am I stuck styling each form individually or is there a process to create a sitewide CSS for Gravity Forms?

I would like to create a basic style for forms that I use on all of my websites so that I only have to tweak around the edges for each site. As it stands now, every form on every page of every site needs custom style.

**Comment by gilesholder** [comment]
Use essential add-ons plugin as this does the trick. I doubt gravity forms styling will ever be added to hello as it's such a light theme and elementor has its own form builder which has full styling options.
