### ISSUE TITLE
Hello Theme + Woocommerce Single Product

### ISSUE THREAD

**Issue by exolon82** [elementor/hello-theme#132]
Hi guys
I have problem , i need to add a product gallery slider in the single product page,  how?  i have found this plugin
https://wordpress.org/plugins/woo-product-gallery-slider/ but not working with hellotheme

**Comment by gilesholder** [comment]
This functionality does not exist in Elementor. I would consider using a third-party plugin to extend the functionality. Essential Addons, Crocobloc etc all have this functionality as a widget.
