### ISSUE TITLE
Make a standard main wrapper for page content...

### ISSUE THREAD

**Issue by nerdtech** [elementor/hello-theme#133]
hey,

I love the hello theme, it's fast, bare-bones and works well with elementor. However there are some plugins that require a main content wrapper (ID or class) to be on every type of page (main content only excluding header and footer templates) in order to function correctly, example (smooth transition widget) > 

[https://docs.dynamic.ooo/article/149-html-structure-of-themes](https://docs.dynamic.ooo/article/149-html-structure-of-themes)

Most other themes seem to have this so I am asking if this can be introduced to a future version of the hello theme. Also in the time-being is there any way to add a main content wrapper to the hello theme via functions.php file?

thanks.

**Comment by Bovelett** [comment]
+1 !

**Comment by ofmarconi** [comment]
+1

**Comment by arielk** [comment]
Fixed in the v2.5.0, thanks for your feedback!
