### ISSUE TITLE
Pink colour hiperlink

### ISSUE THREAD

**Issue by BrunaQuadros** [elementor/hello-theme#134]
Hi everyone! I am trying to change the hyperlink pink colour from my website - tried inspect - CSS but it doesn't appear there, global themes, the appearance from wordpress and nothing seems to solve it.
Any idea whats happening?
Thank you!
<img width="771" alt="Screenshot 2020-12-03 at 17 14 30" src="https://user-images.githubusercontent.com/75440154/101056198-04ab6600-358b-11eb-8410-f0d93653f1d2.png">

**Comment by gilesholder** [comment]
Just go into theme builder and change the colour under the link colour section of typography. This will globally change it. Or use selector CSS if you just wish to change in one instance.
