### ISSUE TITLE
Why should the title of the comment block be an h2 by obligation?

### ISSUE THREAD

**Issue by ciltocruz** [elementor/hello-theme#140]
Hi.

I have seen that hello theme puts the headline in the comments as `h2` replacing the `h3` that comes by default in wordpress.

So far good. Now I have a problem.

I want to modify that `h2` by a `span` without modifying the original template.

I have added this code in my functions.php:

```
function wpdocs_set_comment_form_defaults( $defaults ) {
	$defaults['title_reply_before'] = '<span id="reply-title" class="comment-reply-title">';
        $defaults['title_reply_after'] = '</span>';     
    return $defaults;
}
add_filter( 'comment_form_defaults', 'wpdocs_set_comment_form_defaults' );
```

The problem that I detect is that the hello-theme template code always takes precedence with what is put in the functions.php.

Why is this happening?

How can I modify that h2 without removing this code snippet from the template?
This doesn't work because args always take precedence.

```
<?php
comment_form(
	array(
		'title_reply_before' => '<h2 id="reply-title" class="comment-reply-title">',
		'title_reply_after'  => '</h2>',
	)
);
?>
```

But with this it works correctly:

```
<? php
comment_form ();
?>
```

I hope I have correctly explained what I mean.

Thank you.

**Comment by ciltocruz** [comment]
up!

**Comment by ciltocruz** [comment]
up!

**Comment by arielk** [comment]
This should be done using a child theme: https://developer.wordpress.org/themes/advanced-topics/child-themes/

Just copy /paste the `comments.php` and edit what you need.
