### ISSUE TITLE
GNU Licensing and usage

### ISSUE THREAD

**Issue by zealforwisdom** [elementor/hello-theme#143]
Excellent work on this starter theme. Thank you. 

I'm interested in contributing to this project and I'm also seeking a framework to use for a WordPress theme. 

I'd like to support my efforts by selling the final version online or on a marketplace. Does your GNU General Public License v3 License allow this? 

What do I need be know before I get started?

Thank you kindly. Looking forward to sharing my work with everyone.

**Comment by arielk** [comment]
Good question, I'm not sure I know how to answer you well, please consult with the official WordPress theme team.
