### ISSUE TITLE
💡Transparent Header Conditions

### ISSUE THREAD

**Issue by nreljed** [elementor/hello-theme#156]
[Transparent Header](https://creativethemes.com/blocksy/docs/header-builder/transparent-header/)
Is it possible to add or do a similar function for hello theme?

the idea as shown [here](https://demo.creativethemes.com/blocksy/homi/)

You have one unique header but the transparent version (of the same header) only applies in the defined area (homepage for ex)
I guess the css on the elements applies following the conditions.
This will free us from a lot of trouble finding codes and scripts for the headers

![options](https://user-images.githubusercontent.com/82481592/120534104-c24fce00-c3e1-11eb-8699-485f314f4002.png)

![transp](https://user-images.githubusercontent.com/82481592/120534112-c54abe80-c3e1-11eb-91e7-2741bd199fb3.png)

**Comment by diegoALCE95** [comment]
I agree, it would be nice to a lot of people; however, when you say _"This will free us from a lot of trouble finding codes and scripts for the headers"_ , the recent Elementor funcionality to add Custom code, isn't supposed to handle that?  Under Elementor > Custom code.

**Comment by nicholaszein** [comment]
Hi @nreljed!

Thank you for sharing your suggestion! 

Although it sounds like a great idea for multi-purpose, and highly customizable themes such as Blocksy, having advanced features for handling header effects does not fit quite exactly with the goal we have in mind for the Hello Elementor theme, which is to be minimalist, and lightweight, focused on being a blank canvas for you to build your site's with Elementor (or any other page builder), without interfering with the builder's design. 

Elementor, for example, offers the option to apply sticky effects, or position your elements in the page in a way that would result exactly on what you're suggesting for the Hello Elementor theme, allowing you to create a pixel perfect header with all the elements that matter to you, without any constraints a theme would bring.

For now, our focus will continue to offer a minimalistic theme with as few settings and opinionated design as possible so you can use Elementor to build your perfect site from header to footer. 

Nonetheless we appreciate your interest in improving the Hello Elementor theme! 🙏

Kind regards
