### ISSUE TITLE
Footer info that didn't exist before now seen publicly in 2.4 of Hello Theme... site-footer dynamic-footer footer-has-copyright

### ISSUE THREAD

**Issue by d19dotca** [elementor/hello-theme#171]
I've been hesitant to upgrade to Hello Theme 2.4 and so did it first on a minor website after testing in a couple of sites. 

Unfortunately it seems that the new update 2.4 has modified the content on this website by displaying a "site-footer dynamic-footer footer-has-copyright" section which did not exist prior to this update. I don't see an easy way to disable it but am still working on finding a way. I may just add some CSS to manually hide it for now, but this has me "on hold" from updating any further websites for fear this same random footer content will appear. 

Why did the Hello Theme add a footer to the page? Was it perhaps because a Footer hadn't been defined in the Elementor Theme Builder yet for this website so it 'filled in the blanks' so-to-speak? If so, this seems like poor behaviour that should be changed to never force new content onto a website. And otherwise it seems like a defect.

**Comment by d19dotca** [comment]
Update: I quickly added a blank footer via the Elementor Theme Builder, and sure enough that took away the behaviour. So it seems that the Hello Theme 2.4 version is filling in an automatic footer section with the title of the page which is really not acceptable behaviour for a theme update to do. This behaviour should really be changed ASAP, unless I've misunderstood something about it.

**Comment by shilo-ey** [comment]
@d19dotca thanks, can you please share the steps you made to recreate this issue?

you can disable the hello theme header and footer by going to Elementor - Settings - Experiments tab and disable this experiment.

**Comment by d19dotca** [comment]
Sorry @shilo-ey , I should have included those details earlier.  There was only really one step to introducing the behaviour though... update the theme. 

Here's how to reproduce it:

1. Install Hello Theme 2.3 (not 2.4)
2. Create a Header site part in the Elementor Theme Builder, ensure there is no Footer site part created yet
3. Upgrade to Hello Theme 2.4
4. View the homepage and you'll find the site title at the very bottom left and "All rights reserved" in the bottom right, the Hello Theme 2.4 basically creates a basic footer since the Footer site part was missing from the Elementor Theme Builder earlier

I proceeded with updating all of my client sites after determining the root cause. This was fine on almost 20+ websites where I had both a Header and Footer site part created already using the Elementor Theme Builder, but the issue was seen when updating the Hello Theme on about 3 of my sites which didn't actually have a Footer defined yet in the Elementor Theme Builder. 

My work around was to simply create a blank Footer via the Elementor Theme Builder which then removed the basic footer the Hello Theme injected into the website. While the experiment could be disabled, eventually (presumably) that experiment won't exist in the future and it'll be permanently added to the theme, so I felt the better method was to simply create a blank Footer via the Elementor Theme Builder. 

My expectation is that if there is no Header or Footer defined in the Hello Theme 2.4 itself, then it should not be forcing content into either of them and rely on what is created in Elementor already. Unfortunately right now it seems the Hello Theme makes its own content if it detects a missing Footer (and presumably Header too) from the Elementor Theme Builder. That's not an appropriate behaviour, at least in my opinion. Updating the Hello Theme should not change the content of the website, which it unfortunately does by making its own basic Footer on sites without a predefined Footer site part already.

**Comment by shilo-ey** [comment]
You are correct, we are examining this issue and will release a hotfix asap

Thanks

**Comment by arielk** [comment]
Fixed in 2.4.1 - 2021-07-07
Fix: Hello Theme Header & Footer experiment should be inactive for existing sites

Thanks @d19dotca !
