### ISSUE TITLE
Based On Versions - Out Of Date

### ISSUE THREAD

**Issue by gilesholder** [elementor/hello-theme#179]
Hi there, 

I noticed Hello declares the following: 
"Based on Normalize.css v8.0.0, HTML5 Boilerplate v6.1.0, & Bootstrap Reboot v4.1.0"

Newer versions are available of these:
- Normalize.css - Current: 8.0.0 - Latest: 8.0.1
- HTML5 Boilerplate - Current: 6.1.0 May 2018 - Latest: 8.0.0 June 2020
- Boostrap Reboot - Current: 4.1.0 - Latest 5.1.3

Are these going to be considered in the future?

Also, the theme declares that it requires PHP 5.6. 
WordPress requirements [here](https://en-gb.wordpress.org/about/requirements/) reference PHP 7.4+ should be supported. Would it not be worth removing PHP 5.6 support and clearing up the code a bit? Especially as PHP 8.1 is out in a few days.

Cheers.

**Comment by lensbreak** [comment]
Just was about to write the same thing and discovered this post over the search. We need latest Bootstrap version ASAP for some projects where we migrate the websites to Elementor Pro + Hello Theme.
Right now we can not do that and it is a bit scary that Elementor seems not to take care of this theme but promoting it as the "best theme" while using a bootstrap version from 9 Apr 2018... really?

**Comment by lensbreak** [comment]
@arielk @nuritsha 
Any news? We need [Boostrap Reboot latest 5.1.3](https://getbootstrap.com/docs/5.1/content/reboot/) to be implemented on the hello theme asap. I hope this theme is not getting abandoned by elementor

Thank you for your attention.

**Comment by arielk** [comment]
Hi @lensbreak @gilesholder 

Our reset.scss code was inspired by several open source libraries but there is no dependency between these libraries and Hello Theme. Just to be clear I changed the credit line to avoid misunderstandings.

In addition, there is full compatibility with newer PHP versions (7.4 / 8.0), style.css only declares **at least** version 5.6

Thanks
