### ISSUE TITLE
Hello Elementor 2.4.2 breaks Gravity form CSV export

### ISSUE THREAD

**Issue by ritsute** [elementor/hello-theme#185]
Hello Elementor 2.4.2 breaks Gravity form CSV export.

CSV export seems corrupted on initial glance but on closer look, there is an additional blank line added on line 1 in the CSV exported.
Problem went away on roll back to 2.4.1.

Tested on a clean Wordpress install with the following theme and plugins:

Active: Hello Elementor Child,
Hello Elementor

Elementor
Version 3.5.3, 
Elementor Pro
Version 3.5.2,
Gravity Forms
Version 2.5.15.4

**Comment by rami-elementor** [comment]
Sounds like a Gravity Forms issue.

The theme doesn't control the way Gravity Forms CSV exports work.

Please contact Gravity Forms support.
