### ISSUE TITLE
themes.json Support

### ISSUE THREAD

**Issue by gmariani** [elementor/hello-theme#192]
It looks like there are some features in base gutenberg that are disabled by the absense of a themes.json file. We primarily use elementor to theme the site but use gutenberg for the content. But I'm missing column padding because the feature is not enabled: https://github.com/WordPress/gutenberg/issues/24874

Could you please consider improving gutenberg support?

**Comment by arielk** [comment]
I merged this issue with another issue [###](https://github.com/elementor/hello-theme/issues/189) in the same subject so we could deal with it more efficiently. 

Thanks for your feedback!
