### ISSUE TITLE
I am asking for urgent updates .... Store page / product list

### ISSUE THREAD

**Issue by DanielCyran** [elementor/hello-theme#195]
I am asking for urgent updates ....
Store page / product list

pagination is displayed only at the bottom of the product list ....
It should also appear at the top of the product list ....

it is inconvenient because you have to go to the very bottom of the store's page to change pagination

**Comment by arielk** [comment]
It's something related to WooCommerce not to the theme itself, I'm not sure what we can do for this request.

Thanks for your feedback!

**Comment by DanielCyran** [comment]
other themes don't have this problem

niedz., 10 lip 2022, 13:38 użytkownik Ariel Klikstein <
***@***.***> napisał:
