### ISSUE TITLE
Fatal error when deactivating Elementor plugin

### ISSUE THREAD

**Issue by AlexMartosP** [elementor/hello-theme#198]
I have a child theme of the Hello theme.
When I deactivate the Elementor plugin I get a fatal error that breaks the site.

The error is this "Uncaught Error: Class 'Elementor \Plugin' not found in" the file it is referring to is "elementor-functions.php".

Any suggestions?

**Comment by arielk** [comment]
We have just released a new version of Hello Theme, please let us know if the error still appears
