### ISSUE TITLE
How to remove the website's title from the tab of the sub-pages.

### ISSUE THREAD

**Issue by 42piratas** [elementor/hello-theme#229]
Hi there! I'm using the Hello theme, and I would like to remove the website's title from the tab when I'm on other pages.

The website's title still should still appear on the homepage's tab, though; it should only disappear from the subpages.

Currently:
Homepage's tab displays: "<websiteTitle>"
Subpages' tabs display: "<subpageTitle> - <websiteTitle>"

I want to remove the "- <websiteTitle>" part from the subpages' tabs.

Expected result:
Homepage's tab displays: "<websiteTitle>"
Subpages' tabs display: "<subpageTitle>"

Thanks!

**Comment by rami-elementor** [comment]
Not if this related to the theme, try installing SEO plugin like Yoast or Rank Math to control the page `<title>` tag.

This should give you control over the page title you see on the browser tab.
