### ISSUE TITLE
WHY???  $content_width = 800; // Pixels.

### ISSUE THREAD

**Issue by RonR-WebDesign** [elementor/hello-theme#237]
I chased this for days.  I would set the Large Image Size in Media Settings to 1024 and it would only show 800px.  I finally found this in the readme.txt:

add_filter( 'hello_elementor_content_width', '__return_false' );

That fixed it...  sheesh.   WHY???

More info on Content Width [HERE](https://codex.wordpress.org/Content_Width)

**Comment by rami-elementor** [comment]
To change the content width, see this dev docs:

https://developers.elementor.com/docs/hello-elementor-theme/hello_elementor_content_width/
