### ISSUE TITLE
Skip to content button has a blank href

### ISSUE THREAD

**Issue by JboyJW** [elementor/hello-theme#276]
I'm using Hello Elementor 2.7.0

Filters have been added to the header.php to allow customization of whether the Skip to content link is enabled and what the link should be.  The hello_elementor_skip_link_url filter is good and set to #content by default, but the implementation of the link value is missing an echo.  So currently the skip link always has a blank href.

Current start of line 31:
`<a class="skip-link screen-reader-text" href="<?php esc_url( $skip_link_url ); ?>">`

Needs to be:
`<a class="skip-link screen-reader-text" href="<?php echo esc_url( $skip_link_url ); ?>">`

**Comment by arielk** [comment]
https://github.com/elementor/hello-theme/releases/tag/v2.7.1

**Comment by cmeurer** [comment]
This is the code I already have in Hello Elementor (header.php) and it still does not work. Is there a fix for this?
