### ISSUE TITLE
The hamburger menu didn't show in guest mobile

### ISSUE THREAD

**Issue by aghayedigital** [elementor/hello-theme#294]
![1212](https://github.com/elementor/hello-theme/assets/65608338/f7015fa7-7c77-4ea5-935b-2c01a0991571)
Hi 
I use hello-Elementor in my project
this one https://gearboxbaz.com/
and I have some problems with the menu
for example 
-The hamburger menu didn't show on guest mobile (on the blog page)
but when I click on it, it suddenly shows
-Levels of the menu didn't work correctly

see this page
https://gearboxbaz.com/changan/%d8%aa%d8%b9%d9%85%db%8c%d8%b1-%da%af%db%8c%d8%b1%d8%a8%da%a9%d8%b3-%d8%a7%d8%aa%d9%88%d9%85%d8%a7%d8%aa%db%8c%da%a9-%da%86%d8%a7%d9%86%da%af%d8%a7%d9%86

**Comment by rami-elementor** [comment]
Related to https://github.com/elementor/hello-theme/issues/369

Fixed in [v3.1.0](https://github.com/elementor/hello-theme/pull/388)
