### ISSUE TITLE
Default pink still overrides Global styles and custom CSS

### ISSUE THREAD

**Issue by Pink-c36** [elementor/hello-theme#298]
How do I get rid of #c36, aka rgb(204, 51, 102), finding its way onto random elements?
I changed global styles so no element defaults to that dreaded pink.
I made sure elements are assigned a color so they don't inherit it.
I added custom CSS.
I made sure cache & related stuff is cleared after all of the above.
It still shows up in a few places.

**Is there a way to target that color specifically and change it?**

**Comment by creativeart** [comment]
Did you check that ? https://elementor.com/help/change-link-color/
There is a link color in the theme style.

**Comment by mateitudor** [comment]
Can confirm this bug, if "Elementor colors" are disabled it still displays that pink.
