### ISSUE TITLE
Category Thumnbnails

### ISSUE THREAD

**Issue by bazeboiee** [elementor/hello-theme#322]
Just wondering how I could add Category Thumbnails to Categories as they are a useful thing to be able to use for page templates. I can't seem to get it working with the code I tried to include in my functions file:

if(function_exists('add_theme_support')) {
	add_theme_support('category-thumbnails');
}

Any thoughts?

**Comment by rami-elementor** [comment]
Create a [child theme](https://github.com/elementor/hello-theme-child) for your Hello Theme and add this code snippet to the functions.php file.
