### ISSUE TITLE
/assets/js/hello-frontend.min.js is not minified

### ISSUE THREAD

**Issue by Kiv4h** [elementor/hello-theme#419]
Contrary to what the file name suggests, the content of the file is not minified. SEO tools such as Semrush therefore report a problem every time. This should be a simple fix in deployment.

Sample: https://bytehaus.de/wp-content/themes/hello-elementor/assets/js/hello-frontend.min.js?ver=3.1.1

**Comment by rami-elementor** [comment]
@Kiv4h, thank you for bringing this to our attention.

I've checked this and you are correct, the original file and the minified file are the same:

- https://themes.trac.wordpress.org/browser/hello-elementor/3.1.1/assets/js/hello-frontend.js
- https://themes.trac.wordpress.org/browser/hello-elementor/3.1.1/assets/js/hello-frontend.min.js

We will fix this bug in our next release.

**Comment by rami-elementor** [comment]
Fixed in v3.2.0
