### ISSUE TITLE
WordPress 6.7 warns about loading translations too early 

### ISSUE THREAD

**Issue by gabriele-serafino** [elementor/hello-theme#423]
Since WordPress version 6.7.0, the following Notice appears on the top of the page, preventing most of the pages to load the rest of the content.

> Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the hello-elementor domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in /var/www/html/wp-includes/functions.php on line 6114

Issue verified on plugins versions: 3.0.1, 3.1.1

**Comment by MiaWalkthruit** [comment]
Same here

**Comment by rami-elementor** [comment]
Interesting, according to the message, it's a theme issue:

> Translation loading for the `hello-elementor` domain was triggered too early.

But "Hello Elementor" theme no longer uses `load_theme_textdomain()` method.

**Comment by pingram3541** [comment]
It is an issue because the theme uses translations __() method. Any of these that are called prior to init will cause this error in the debug log file.

In my case it's a lot and I can't disable debugging at the moment.

see: https://make.wordpress.org/core/2024/10/21/i18n-improvements-6-7/

see also: https://github.com/elementor/hello-theme/issues/429

**Comment by rami-elementor** [comment]
> It is an issue because the theme uses translations __() method. Any of these that are called prior to init will cause this error in the debug log file.

Using `__()` method won't trigger the error. The error appears in themes that use `load_theme_textdomain()`, and only when this method is called too early.

WordPress recommend to removing `load_theme_textdomain()`, this way it can automatically load translations when needed (just in time). Pascal Birchler, the author of the post you attached, sent us a Pull Request at the beginning of the year, to remove this method.

Both **Elementor** and **Hello Theme** no longer use this method. Unless you are using an old version of the theme...

**Comment by pingram3541** [comment]
Downloaded straight from this repo 3 days ago. I've updated #429 but have since removed this new translations check from WordPress core until everybody figures out how to calm this storm. It's a problem with thousands of plugins/themes needing correction.
