### ISSUE TITLE
Fatal php error

### ISSUE THREAD

**Issue by cmbc58** [elementor/hello-theme#44]
When trying to create child theme with lilaeamedia child theme configurator plugin - should i be concerned by this?:

Fatal error:  Uncaught Error: Call to undefined function zita_responsive_spacing() in /home/cartmelp/public_html/cmbctest.co.uk/wp-content/plugins/zita-pro/admin/zita-style.php:8
Stack trace:
#0 /home/cartmelp/public_html/cmbctest.co.uk/wp-content/plugins/zita-pro/admin/zita-style.php(1078): zita_pro_custom_style()
#1 /home/cartmelp/public_html/cmbctest.co.uk/wp-includes/class-wp-hook.php(286): zita_pro_scripts('')
#2 /home/cartmelp/public_html/cmbctest.co.uk/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#3 /home/cartmelp/public_html/cmbctest.co.uk/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#4 /home/cartmelp/public_html/cmbctest.co.uk/wp-includes/script-loader.php(2537): do_action('wp_enqueue_scri...')
#5 /home/cartmelp/public_html/cmbctest.co.uk/wp-includes/class-wp-hook.php(286): wp_enqueue_scripts('')
#6 /home/cartmelp/public_html/cmbctest.co.uk/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#7 /home/cartmelp/public_html/cmbctest.co.uk/wp-includes/plugin.php in /home/cartmelp/public_html/cmbctest.co.uk/wp-content/plugins/zita-pro/admin/zita-style.php on line 8

**Comment by I-am-io** [comment]
@cmbc58 
If you look at the error message you can see your problem originates from the **zita-pro** plugin. The plugin tries calling a function which doesn't exist. This results in a fatal error.
