### ISSUE TITLE
Theme update

### ISSUE THREAD

**Issue by lucafagherazzi** [elementor/hello-theme#47]
Hi everyone, I installed the version 2.0.5 of the Hello theme by adding it from the wordpress repo. I noticed that it doesn't update automatically.
Thank you

**Comment by jimbotechsys** [comment]
Mine did but it's not a built-in process on any theme. You either have to add a filter in functions.php, install a plugin such as Automatic Updates or, like me, rely on Installatron in cPanel at my hosting provider. Reference [https://www.wpbeginner.com/plugins/how-to-enable-automatic-updates-for-wordpress-plugins/] for information.

**Comment by lucafagherazzi** [comment]
I badly explained myself. I mean that in the wordpress repo the last version available is 2.0.5 but in reality we are at 2.0.7.

**Comment by jimbotechsys** [comment]
Sorry about that! I see 2.0.8 was just pushed. Let us wait and see.

**Comment by lucafagherazzi** [comment]
Thank you! Now the 2.0.6 update appears. Let's wait....

**Comment by VerdiH** [comment]
All fine on my end. Seems this one can be marked as solved.

**Comment by lucafagherazzi** [comment]
Hi, I also updated all the sites to 2.0.6, but I think there is something wrong. Maybe I'm wrong.

![001](https://user-images.githubusercontent.com/40598133/58548599-ea603180-8209-11e9-8e36-73e63136b04d.jpg)
![002](https://user-images.githubusercontent.com/40598133/58548615-f0561280-8209-11e9-8e43-7f820d69fff8.jpg)

**Comment by nuritsha** [comment]
Hi @lucafagherazzi,

Sorry for the confusion,
the latest version is 2.0.6, as appears in the WordPress repo.

**Comment by lucafagherazzi** [comment]
Perfect, thank you very much!
