### ISSUE TITLE
Style over rider on woocommerce category listing

### ISSUE THREAD

**Issue by damarusama** [elementor/hello-theme#48]
When using this theme with elementor pro and woocommerce the style from the category listing cannot be applied as Woocommerce style takes over. 

When I use 2019 from wordpress the proper style shows up. 

When I de-activate all the plugins and only keep elementor, elementor pro and woocommerce the same behaviour happens. 

You can see in here : 
![style](https://user-images.githubusercontent.com/296989/58584426-7e82c680-8213-11e9-9f40-8093c5ce66c7.png)

how the woocommerce style takes over the inline elementor style. It seems like the CSS class is not precise within the Hello theme.

**Comment by nuritsha** [comment]
Hi @damarusama ,

Thank you for pointing out this issue, the fix will be part of the next **Elementor Pro** patch release.
