### ISSUE TITLE
iPhone X Landscape Compatibility

### ISSUE THREAD

**Issue by not-enough-yet** [elementor/hello-theme#49]
Due to the provision Apple made for the iPhone X notch, all websites have white margin bars added to them when in landscape mode. Please add `viewport-fit=cover` to the `<meta>` tag to fix it.

**Comment by not-enough-yet** [comment]
Just to clarify and follow up on this issue I am attaching visuals.

**This is what it looks like at the moment:**
![Issue](https://user-images.githubusercontent.com/51179387/61011768-c0357f80-a330-11e9-9696-d47fce6a6476.jpg)

**This is what it should look like:**
![Fixed](https://user-images.githubusercontent.com/51179387/61011767-c0357f80-a330-11e9-8a8c-4d71372a5efc.jpg)

**Comment by nuritsha** [comment]
Hi @not-enough-yet,

Please check the next version of the theme, it will include a new filter designed to address your request.

Thanks!

**Comment by not-enough-yet** [comment]
@nuritsha,

Thanks for the help! I can't seem to get it to work. Could you explain how to add `viewport-fit=cover` to what already exists? Also shouldn't this change be added to the code as the default?

Thank you!

**Comment by nuritsha** [comment]
Hi @not-enough-yet,
To use the new filter you need implement it in your child theme's `functions.php`.
You can use this snippet as inspiration:
 ```php
function my_viewport_content( $content ) {
	$my_viewport_content = 'viewport-fit=cover';
	// if you need any of the default settings use the following (note the comma separator):
	// return $content .  ', ' . $my_viewport_content;
	// if you need only the new settings, use this:
	return $my_viewport_content;
}
add_filter( 'hello_elementor_viewport_content', 'my_viewport_content' );
```

**Comment by ramiy** [comment]
You can also add your own meta tag to override the previous meta tag:
```
function custom_viewport() {
    ?>
    <meta name="viewport" content="viewport-fit=cover"
    <?php
}
add_action('wp_head', 'custom_viewport');
```

**Comment by philmatt** [comment]
+1

I would like better iPhone compatibility without the need to create a child-theme. Is that possible with Hello Theme?

**Comment by noisybird** [comment]
> Hi @not-enough-yet,
> To use the new filter you need implement it in your child theme's `functions.php`.
> You can use this snippet as inspiration:
> 
> ```
> function my_viewport_content( $content ) {
>    $my_viewport_content = 'viewport-fit=cover';
>    // if you need any of the default settings use the following (note the comma separator):
>    // return $content .  ', ' . $my_viewport_content;
>    // if you need only the new settings, use this:
>    return $my_viewport_content;
> }
> add_filter( 'hello_elementor_viewport_content', 'my_viewport_content' );
> ```

Hmmm, thanks, but it also modifies the design in portrait mode, it does not only affect the landscape mode of the iPhone X. The header becomes all tiny in portrait mode.

**Comment by JPOak** [comment]
I just tried out Hello Elementor and noticed this. It must be more than not using viewport-fit=cover . I've used Elementor with other themes and these bars don't appear and the aren't using viewport-fit=cover . Ideas anyone?
