### ISSUE TITLE
Installing jquery selectric 

### ISSUE THREAD

**Issue by neosaveme** [elementor/hello-theme#50]
Hello, I have a big issue here. 
I can't figure out how to install this https://selectric.js.org/
On hello theme. 
Can someone please explain to me how I can do that?

**Comment by drawcard** [comment]
Best way is to use the [Hello child theme](https://github.com/elementor/hello-theme-child) and add your script to it, then [enqueue the script & its CSS](https://developer.wordpress.org/themes/basics/including-css-javascript/#enqueuing-scripts-and-styles) in the functions.php file.
