### ISSUE TITLE
Wrap page content in .elementor-container

### ISSUE THREAD

**Issue by lcswillems** [elementor/hello-theme#51]
Hi,

By default, my page content takes the full width of the page. Is it possible to wrap it inside a .elementor-container without making templates?

Lucas

**Comment by Webtica** [comment]
+1 would like this too. As with non elementor pages they take 100% of the page width.

**Comment by nuritsha** [comment]
Hi @lcswillems and @Webtica ,

Thank you for you suggestion, however, adding the class will not have the impact you wish.
For performance sake, the Elementor stylesheet is loaded only in pages that are built with Elementor.

Thanks!
