### ISSUE TITLE
Hello Theme not in Wordpress Repository

### ISSUE THREAD

**Issue by davidzangardi** [elementor/hello-theme#52]
The Hello Theme is no longer showing up in the official Wordpress Repository.  When you search Hello Elementor it just says "No themes found. Try a different search."

**Comment by Xhale1** [comment]
I too am having this issue. None of the official links from Elementor's website to download Hello works.

**Comment by nuritsha** [comment]
Hi @davidzangardi and @Xhale1,

The theme was removed from the repo by a WP admin. We are working diligently to bring it back.

**Comment by momo-fr** [comment]
"The general consensus from the team is that this theme should again be suspended (even after they have viewed the update shared today) until it can fulfil the expectation of it being a functional and viable theme in it's own right - without the NEED for a plugin."

**Comment by nuritsha** [comment]
Hi @momo-fr,
We are working on it. Hopefully we'll be able to satisfy the Theme Review Team requests soon.

**Comment by redpik** [comment]
It's here : https://wordpress.org/themes/hello-elementor/

**Comment by nuritsha** [comment]
yes it's back :)
