### ISSUE TITLE
Link color

### ISSUE THREAD

**Issue by pless84** [elementor/hello-theme#57]
How do I change the red color for links? Do I need to edit scss files or is there a theme option I have overlooked.

**Comment by nuritsha** [comment]
Hi @pless84 ,
Links color can be changed either thru style.css (or scss, but then you'll need to rebuild it with grunt) or, the easiest thru Elementor, assuming you have it installed.

**Comment by pless84** [comment]
Can I change it globally via Elementor?

**Comment by nuritsha** [comment]
With Elementor the change will not be global (we are working on it, but it will take some time to get there). If you want a global change, you can use the WordPress customizer.

**Comment by pless84** [comment]
Ok thanks :)

**Comment by Libero96** [comment]
Sorry for opening this closed topic, but I cannot find the setting to change the link color in the Wordpress customizer when using the Elementor Hello theme. 

The only options I have in the Wordpress customizer are:
- Site identity
- Menus
- Homepage settings
- Extra CSS

My site has quite some dark brown and orange in it, so these red links are really popping out.

**Comment by cavalierlife** [comment]
Please see the FAQ at https://docs.elementor.com/article/583-hello-theme for examples on how to do this.

**Comment by Libero96** [comment]
@cavalierlife Thanks a lot! I removed my comment as I wasn't sure if it would publish under a closed thread.

OK, if I just copy that code in the Additional CSS tab of the customizer it will work. I will try that now. Again, thanks for your answer!

**Comment by brett-hamburger** [comment]
Cavierlife,
Thank you!!!  You Rock!
Brett

**Comment by morevnaproject** [comment]
Now it is possible to define theme style globally through Elementor - https://elementor.com/blog/introducing-theme-style/

**Comment by fippy** [comment]
This is great step by Elementor, but the 'global theme styling' (GTS) still has some issues... 

Fore example their own Hello Theme sets up styling for links, titles, buttons, etc, but these are only overridden by GTS if you specifically set them. E.g the Hello Theme implements a red border around around buttons by default. Setting the border to none in GTS does not override the styling in the theme stylesheet. 

Just be aware, until Elementor test and improve GTS as you may still need to use both GTS and your own childtheme stylesheet.
