### ISSUE TITLE
Remove page title 

### ISSUE THREAD

**Issue by yaniv691** [elementor/hello-theme#59]
Could there be an option to remove the H1 tag (.entry-title) from pages/posts? When using Elementor, I usually give pages their own H1 tags using a widget, or adding a widget to the single template. 

I would be great if the default H1 tag could be removed (not printed at all, not just hiding it with CSS display: none).

Thanks!

**Comment by badcat** [comment]
I'm interested too...  Doesn't clicking the Gear icon to get to Page Settings allow you to Hide the Title for pages? Or did I misunderstand?

![h1](https://user-images.githubusercontent.com/26096/59033121-f06f9700-8835-11e9-9dd5-756e369bc7ba.png)

**Comment by yaniv691** [comment]
@badcat Your suggestion is correct, but it's rather tedious to do on a lot of page. It would be great to have a global setting (or filter like @nuritsha commited to her branch ;-) )

**Comment by bigwilliam** [comment]
@yaniv691 I know you said you don't want to use CSS, but that's the quickest way to do this globally, without adding bloat to the theme (which I assume is meant to be lightweight). 

It's easy to go into WP Customizer and add global CSS:

```
.entry-title {
  display: none;
}
```

**Comment by yaniv691** [comment]
@bigwilliam The reason I want to avoid CSS is because I don't want multiple h1 tags (one inserted by the theme another by me). Even through the user will only see one heading, this is bad practice in terms of accessibility (specifically screen readers) and SEO. Also, I don't want unnecessary HTML markup on the page which cannot be seen.

The theme supposed to be lightweight but should also provide some basic filters to customize some critical parts.

**Comment by nuritsha** [comment]
Hi @yaniv691, @badcat and @bigwilliam,

Thank you for your suggestions,

Please take a look at the new filter introduced in version 2.1.0:
`'hello_elementor_page_title'`,
You can add it to you functions.php and prevent the theme from printing h1 tags throughout the site, just follow the instruction in the theme's `readme`.

**Comment by yaniv691** [comment]
Thank you very much @nuritsha. This is exactly what I needed - simple hooks.

**Comment by RomainJM** [comment]
There is a problem now, we have a empty header.

Can this filter include header too ?

**Comment by nuritsha** [comment]
@RomainJM - thank you for pointing that out. Will be included in the next release.

**Comment by MaximPro** [comment]
Please add this function to the customizer finaly.
Everyone waits, because no one wants to use extra hooks - no normal user does that and the catch is that elementor is primary developed for normal users.
I will add the hook, however it would be still very useful!

**Comment by philmatt** [comment]
+1

**Comment by All44** [comment]
+1

**Comment by ashkan-ahmadi** [comment]
Add the following line to your functions.php to hide the title from all the pages on your website:

`add_filter( 'hello_elementor_page_title', '__return_false' );`

**Comment by Dubidubiduu** [comment]
> 
> 
> Add the following line to your functions.php to hide the title from all the pages on your website:
> 
> `add_filter( 'hello_elementor_page_title', '__return_false' );`

And then readd that everytime the themes get an update? No, it needs to be a setting.

**Comment by badcat** [comment]
> And then readd that everytime the themes get an update? No, it needs to be a setting.

Perhaps adding that to a child theme functions file makes more sense.

**Comment by ashkan-ahmadi** [comment]
> > Add the following line to your functions.php to hide the title from all the pages on your website:
> > `add_filter( 'hello_elementor_page_title', '__return_false' );`
> 
> And then readd that everytime the themes get an update? No, it needs to be a setting.

Add it to your child theme's functions.php. The other option is to change the theme's version to a huge number like 99999 so that it will never update. Alternatively, you can create a shell theme yourself. It's not difficult

**Comment by badcat** [comment]
https://elementor.com/blog/wordpress-child-theme/
