### ISSUE TITLE
Compatibility with AMP

### ISSUE THREAD

**Issue by Josimarcsilva** [elementor/hello-theme#62]
Hi,

The world is mobile. Mobile first then.
It would be amazing to have compatibiliade with AMP to make our projects incredibly fast.

There are already solutions in the market that promise this:
https://ampforwp.com/amp-pagebuilder-compatibility/

But I would like to see this in the core of Elementor

**Comment by drawcard** [comment]
This should be optional - I for one don't want AMP on my website :)

**Comment by arielk** [comment]
Long time, but unfortunately, I do not see that we are going to implement these request in the near future, so I close this issue. If we add the options in the future, we'll try to update here.

Thank you for your feedback
