### ISSUE TITLE
Add global colours / styles

### ISSUE THREAD

**Issue by freelancesam** [elementor/hello-theme#66]
I recommend this theme to everybody using elementor but there's no easy way without custom css or 3rd party plugins to set site wide styles (for example, setting the default text link color)

**Comment by nuritsha** [comment]
Hi @freelancesam,
Thank you for pointing out this topic.
You are correct and it is in our roadmap.

**Comment by nuritsha** [comment]
Please follow this feature request here: https://github.com/elementor/elementor/issues/3345
