### ISSUE TITLE
Show version of Hello Theme at CSS query string

### ISSUE THREAD

**Issue by shimsa** [elementor/hello-theme#69]
It could be better showing Hello Theme version instead of WordPress version.

- is better to not reveal WordPress version to hackers
- if Hello Theme CSS change, than it change immediately also visitors in their browser cache

![Snímek z 2019-06-14 09-32-24](https://user-images.githubusercontent.com/7617350/59492965-64d7b500-8e8a-11e9-9dae-2a868f0da4c6.png)

**Comment by nuritsha** [comment]
Hi @shimsa,

Thank you, this is indeed a nice tweak, will be added in one of the next patches.

**Comment by nuritsha** [comment]
please see version 2.1.2.
thanks!
