### ISSUE TITLE
Remove all css option

### ISSUE THREAD

**Issue by steffanhalv** [elementor/hello-theme#71]
It would be really cool if it was an option to disable all styles and javascript, so it was just a 100% plain template alternative where we could design everything our selves. I thought that was the purpose of this template until v. 1.1.0 which made everything harder 😬

It could for example be a switch which had the option enable / disable basic styling and javascript.

**Comment by nuritsha** [comment]
Hi @steffanhalv,

There are two filters you can use to disable loading the theme css:
Use `hello_elementor_enqueue_style` to prevent loading the reset css,
and `hello_elementor_enqueue_theme_style` to prevent loading the theme specific style.
It is recommended that if you remove the reset css (1st hook), remove also the theme css (2nd hook).

Hello theme does not enqueue any javascript.
Thanks!
