### ISSUE TITLE
hello_elementor_content_width not working?

### ISSUE THREAD

**Issue by alriksson** [elementor/hello-theme#77]
How does the filter work? `hello_elementor_content_width`

Did an extreme test to see if it works and it's not. Page template in theme builder set to default.
`add_filter( 'hello_elementor_content_width', '80px' );`

**Comment by nuritsha** [comment]
Hi @alriksson 
This filter sets the value of a global:
`$GLOBALS['content_width']`.
Elementor does not use this variable, however, there are other plugins that do (e.g. Jetpack).
The name of the global is confusing, it DOES NOT defines the content width, but used by to limit embedded images and videos to that width.

If for some reason you do need this global, please note that the filter callback should return int (the line of code you sent will evaluate to a function named `80px` which is not valid in php).

**Comment by alriksson** [comment]
Ok, I thought this set the default width in elementor so instead of editing each section I could globally control this here.
