### ISSUE TITLE
WP admin bar disappeared

### ISSUE THREAD

**Issue by wpsumo** [elementor/hello-theme#78]
Since the last updates, the frontend wp admin bar disappeared. Must be some issue with the php call to the footer?

Right now have to force it with a snippet right now.

```
function admin_bar(){

  if(is_user_logged_in()){
    add_filter( 'show_admin_bar', '__return_true' , 1000 );
  }
}
add_action('init', 'admin_bar' );
```

**Comment by nuritsha** [comment]
Hi @alriksson,
I can't reproduce this issue in my env. 
Do you still experience this problem?

**Comment by alriksson** [comment]
Yes, I do. Still, have to force the admin bar with the php snippet above.
