### ISSUE TITLE
Remove first <h1> tag from default page layout

### ISSUE THREAD

**Issue by artneo7** [elementor/hello-theme#81]
When the page layout is set to default there is a (h1) Home and another (h1) with you page title. 

This could be a SEO improvement for Hello Theme.
![Screen Shot 2019-07-11 at 10 59 43](https://user-images.githubusercontent.com/17693529/61057505-d9d7d500-a3cb-11e9-9931-2530b5150e9d.jpg)

If I choose the Elementor canvas the first (h1) is gone, but so are the header and footer.

**Comment by nuritsha** [comment]
Hi @artneo7,
In v 2.1.2 we introduced a filter that can be used to hide the `h1` tags: 
`hello_elementor_page_title`
You can use it in order to prevent printing the titles without loosing the header & footer.

**Comment by artneo7** [comment]
[Reminder] Add this code to functions.php:
**add_filter( 'hello_elementor_page_title', '__return_false' );**
Thanks again!
