### ISSUE TITLE
Hello Theme Archive Posts Per Page

### ISSUE THREAD

**Issue by Luxamman** [elementor/hello-theme#84]
Hello,

since Elementor Pro uses the theme for deciding how many posts are shown in an archive (https://github.com/elementor/elementor/issues/6336), the Hello Theme should give us the option - or the Elementor Pro Archive widget should be able to do that, because this is very essential for lots of sites.

Thanks!

**Comment by nuritsha** [comment]
Hi @Luxamman,

Thank you for you suggestion.
The Elementor Hello theme is designed as minimal as possible, with the primary goal of providing a lean and efficient foundation for Elementor. Adding additional settings and customizations kind of misses that purpose...
Therefore, at this stage, we do not plan to add the functionality to the theme, we will, however, investigate the options of adding it to the Plugin.
Having said all that, here are two options to control the number of posts in an archive page:
1 - The built-in WordPress way: settings > reading > "Blog pages show at most".
2 - using the `elementor/theme/posts_archive/query_posts/query_vars` filter:
```
function my_archive_limit( $query_vars ) {
    $my_new_limit = 42;
    $query_vars['posts_per_page'] = $my_new_limit;
    return $query_vars;
}
add_filter( 'elementor/theme/posts_archive/query_posts/query_vars', 'my_archive_limit' );
```
