### ISSUE TITLE
Problems inlcuding custom scss

### ISSUE THREAD

**Issue by p3k1n0** [elementor/hello-theme#85]
Hello,
I would like to import in all my porjects a stylesheet with all the 'h' tags and 'body' tag definitions, that overrides the theme and elementor ones. I read the readme.txt, and I tried to follow the instructions but I had some issues.

First, the theme here and the theme that I downloaded form your site, despite being both 2.1.2, have a different tree structure.... only the one in this repository has a scss folder.

So I took the one from this repository and I created a custom folder unders assets\scss and there I put a custom.scss (with the @import syntax) and a rdsus_style.scss file, which is  my custom scss file, with the 'h' and 'body' definitions
At this point I had the files in assets\scss\custom\

The syntax I put in custom.scss is a syntax I found on an older version of your theme:

`rdsud_style style:`
`@import "rdsud_style";`

Then I regenerated the css in elementor but nothing. It didn't work.
What I did wrong, could you tell me please?

Thank you very much, and keep up with the good work

**Comment by nuritsha** [comment]
Hi @p3k1n0,

We no longer support the option to add css thru the `custom` directory, 
to add you custom code, we recommend creating a child theme.
I'll make sure the readme is updated, sorry for the confusion...

**Comment by p3k1n0** [comment]
thank you
