### ISSUE TITLE
elementor-hello-theme: css variables causing error

### ISSUE THREAD

**Issue by sambbaron** [elementor/hello-theme#89]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
In the 'elementor-hello-theme -> Customizer -> Additional CSS', using css variables causes the css text editor to throw errors, but the css is executed properly.

![elementor-screenshot](https://user-images.githubusercontent.com/10456742/57573323-d4193f80-73da-11e9-9a27-1095e080d554.PNG)

**Comment by nuritsha** [comment]
Hi @sambbaron,

Unfortunately, this is the way the WordPress css editor in the customizer works, it is not unique to the Hello Elementor theme.

Thanks!
