### ISSUE TITLE
Text Editor Widget: Large images with captions break theme responsiveness

### ISSUE THREAD

**Issue by ramiy** [elementor/hello-theme#91]
## The Issue

When we add large images (with captions) inside the "Text Editor" widget, the mobile view breaks.

I guess it happens because the theme doesn't use the CSS required every theme should use:
https://codex.wordpress.org/CSS#WordPress_Generated_Classes

## Recreate

To recreate the issue with **Elementor Hello Theme**:

1. Create a new page/post and edit it with Elementor.
2. Add a new "Text Editor" widget.
3. Within the wp-editor add an image between the paragraphs using the "Add Media" button.
4. Select a large image and add a caption to the image.
5. Now switch to mobile view using Elementor responsive display. Or view the page in your mobile phone.

**The issue**: the image is wider then the port view. The site has a horizontal scrollbar.

## The Solution

The solution is to add `.wp-caption{ max-width: 100%; }` or `figure{ max-width: 100%; }` in case the user manually or problematically removes the class.

**Comment by ramiy** [comment]
@arielk @matipojo @bainternet @KingYes @joshmarom

**Comment by matipojo** [comment]
@nuritsha

**Comment by nuritsha** [comment]
@ramiy ,
Thanks, handling.
