### ISSUE TITLE
Video in place of featured image on Blog Archive Pages

### ISSUE THREAD

**Issue by Josimarcsilva** [elementor/hello-theme#94]
Hi,
I have a suggestion for improvement.

The world is currently driven by video. The largest blog and news site use videos in their publications. The Elementor plugin and Hello Theme need to support videos in place of the featured image on Blog Archive Pages.

Teme DIVI has been doing this for a long time. See the example below:
https://www.elegantthemes.com/preview/Divi/blog-masonry/

The images below will illustrate how DIVI is currently doing.

![Video](https://user-images.githubusercontent.com/4340052/65378434-75b87380-dc8e-11e9-864f-e34b6c7aa100.jpg)
![Sugestion1](https://user-images.githubusercontent.com/4340052/65378437-79e49100-dc8e-11e9-82b3-698f5b8bd2df.jpg)
![Sugestion2](https://user-images.githubusercontent.com/4340052/65378439-7cdf8180-dc8e-11e9-9f15-95da4b8b699c.jpg)

**Comment by nuritsha** [comment]
Hi @Josimarcsilva,

Thank you for your suggestion.
This issue is closed since it is out of the scope of the Hello theme.
I have noticed you already opened the same change request in the Elementor plugin repo, thank you for that, that is the correct location.
