### ISSUE TITLE
Hide Title as theme DEFAULT?

### ISSUE THREAD

**Issue by chatpotion** [elementor/hello-theme#95]
Hey, I'm not sure if this is the right place to leave feature requests, I'm not familiar with GitHub.

But something that would be very helpful in Hello Theme would be the option to HIDE TITLE in EVERY post as a default. It's EXTREMELY tedious having to go in after each new page and having to go to the page settings to hide title. I'd like it to forever hide title. The title is ugly and useless at its default and its an extra obstacle to remove before designing the page.

![Screen Shot 2019-09-26 at 11 27 29 AM](https://user-images.githubusercontent.com/55846563/65702223-a7478b00-e050-11e9-82ab-a6d4c574cde1.jpg)

**Comment by nuritsha** [comment]
Hi @chatpotion,
Please see reply to issue #81
