### ISSUE TITLE
Primary colour option

### ISSUE THREAD

**Issue by ryanfurtner** [elementor/hello-theme#97]
Shouldnt there be a simple option to change the primary theme colour from '#c36'?

**Comment by mbaierl** [comment]
The same applies to links - there is no easy way of overriding the default color option...

**Comment by homesinfra** [comment]
Yes, the pink color on links cant be overridden on elementor. So had to use yellow pencil.

**Comment by nuritsha** [comment]
Hi @ryanfurtner, @mbaierl & @homesinfra,

We are working on a solution for global settings (which will be part of the plugin, not the theme), but it is not ready just yet. 
In the mean time, please use good-old css.

Thanks!

**Comment by nuritsha** [comment]
Duplicate of #57

**Comment by nadworks** [comment]
Sorry, is there an update? Using HELLO a lot, but the lack of global colour over-write is still missing and it's been over a year since this thread was "closed".
