### ISSUE TITLE
WooCommerce Child Page: Filename cannot be empty wc-template-functions.php

### ISSUE THREAD

**Issue by butchewing** [elementor/hello-theme#99]
When I create a Thank you page `/thank-you`, everything works properly. If I create a Thank you page as a subpage `/parent/thank-you`, I get the following errors:

```
Warning: include(): Filename cannot be empty in /public_html/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 49

Warning: include(): Filename cannot be empty in /public_html/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 49

Warning: include(): Failed opening '' for inclusion (include_path='.:/usr/share/php') in /public_html/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 49
```

If I rename the slug from `/thank-you` to `/thanks` everything works properly.

It has something to do with the slug that equals `thank-you` only as a child page.

Each of the pages in this scenario is on a site with WooCommerce, but they are not "WooCommerce shop pages". The only content on these pages is the title.

This error is happening as a strange sort of 404 page.

The exact same thing happens if I try to go to a missing page like `/test/thank-you`. The test page exists but the child thank you page does not. The same errors are displayed. This is true if the /thank-you page exists or not.

**Comment by zeinnicholas** [comment]
Themes do not control the output of the WooCommerce thank you page. To modify it you need to use either a plugin or use custom functions to hook to the page. This means that using a normal page to make a Thank You page won't work. This has nothing to do with either the Hello Elementor theme, or Elementor itself.

Here are some info on how to customize the thank-you page:

https://www.google.com/search?q=woocommerce+how+to+create+a+custom+tank+you+page&rlz=1C1GCEA_enBR853BR853&oq=woocommerce+how+to+create+a+custom+tank+you+page&aqs=chrome..69i57j0l3j69i64l2.14353j0j7&sourceid=chrome&ie=UTF-8

Full disclosure: I'm not from the Elementor staff...

**Comment by butchewing** [comment]
Got it. I'm not trying to create a custom WooCommerce Thank You page. I'm creating a thank you page for a contact form redirect. I have several landing pages each with their own thank you pages. These are all separate from a WooCommerce checkout thank you page.

It seems strange that WooCommerce is reliant on a page with a particular slug `thank-you`. But, I see now that this is a WooCommerce issue, not a theme issue.
